---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-service-app
spec:
  selector:
    matchLabels:
      app: counter-service-app
  template:
    metadata:
      labels:
        app: counter-service-app
    spec:
      containers:
      - name: counter-service-app
        image: k3d-registry.localhost:5000/com.github.agabrys/counter-service:dev
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: counter-service
spec:
  selector:
    app: counter-service-app
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-traefik
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /counter
        pathType: Prefix
        backend:
          service:
            name: counter-service
            port: 
              number: 80
