---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: none-nginx
  labels:
    app: none-nginx
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ignored
  template:
    metadata:
      labels:
        app: ignored
    spec:
      containers:
      - name: ignored
        image: nginx
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "50Mi"
            cpu: "100m"
